### PR TITLE
Separate NA phases

### PR DESCRIPTION
**Pull request by auggiemarignier**
We want to allow the user to just perform the direct search phase of the NA.

Initial idea (quick fix) is to simply make all the parameters related to the appraisal phase optional, and if these are not set simply return the results of the direct search phase.

If we want, we can ultimately have two separate inference tools (more complete fix).  A use case for this would be a user who has some samples from a posterior distribution obtained with some other method, and wants to increase their sample size.  It would also be slightly cleaner for a user who just wants the NA direct search phase.  One issue I see with this is that it would effectively double the work of a user who just wants to do the two phases of the NA, as they would need to essentially go through the CoFI workflow twice.

### CODE REVIEW

**Comment by auggiemarignier** [comment]
Need to give an option to run the direct search in serial, e.g. if the forward model is not pickleable (pygimli....)

**Comment by auggiemarignier** [comment]
I've now split this into 3 different tools:

1. `Neighpy` - runs both phases
2. `NeighpyI` - runs only direct search phase
3. `NeighpyII` - runs only appraisal phase

`Neighpy` calls the methods of `NeighpyI` and `NeighpyII` so there's a fair bit of coupling going on but I think this is the most efficient way to do it to avoid unnecessary code duplication. 

`NeighpyII` takes an `initial_ensemble` and corresponding `logppd` in `InversionOptions`.  These can be from any other sampler.

Still TODO:

- [ ] `NeighpyII` hangs when running in parallel for some reason, but `Neighpy` is fine...
- [ ] Examples of all three in action

**Comment by auggiemarignier** [comment]
@jwhhh this is ready if you want to check it

**Review by jwhhh — APPROVED** [review]
Code all looks good to me! We can merge it once the version restriction is updated.

**Comment by auggiemarignier** [comment]
which version restriction?

**Comment by jwhhh** [comment]
`neighpy=0.1.2` seems to fail the tests as there's no `parallel` argument in the search stage. Which version onwards of neighpy would you recommend cofi to write in `pyproject.toml`?

**Comment by jwhhh** [comment]
It all looks good to me now. Please merge once you think it's ready

**Pull request merged**
